### PR TITLE
Added Original Images And Its Result

### PR DESCRIPTION
**Pull request by Smit1603**
-This PR will resolve issue #12 and #22 
-Current Folder 'Results' consists of sub-folders:

1. Original_Images - It consists of original images on which testing is conducted
2. OpenCV_Images - It consists of clustered images obtained directly using cv2 functions
3. K-Means - It consists of sub-folders
                     K-Means++ - It consists of images obtained utilizing initialization method - "K-Means++"
                     Random_Initialization - It consists of images obtained utilizing initialization method - "Random Initialization"
4. Improved_K-Means - It consists of sub-folders
                                      K-Means++ - It consists of images obtained utilizing initialization method - "K-Means++"
                                      Random_Initialization - It consists of images obtained utilizing initialization method - "Random Initialization"

-Current Folder 'Report' also contains project report.

### CODE REVIEW

**Comment by Dhruv454000** [comment]
@Smit1603 In my opinion you can change the image for set4

**Comment by Smit1603** [comment]
> @Smit1603 In my opinion you can change the image for set4

So should i search for another medical image or normal image will do???

**Comment by Dhruv454000** [comment]
> > @Smit1603 In my opinion you can change the image for set4
> 
> So should i search for another medical image or normal image will do???

any will do

**Comment by Dhruv454000** [comment]
Is it done @Smit1603 ?

**Comment by Smit1603** [comment]
> Is it done @Smit1603 ?

Sorry Sorry , yes will find new image and perform on it till night

**Pull request merged**
